site_name: Republic of Korea Documentation
site_url: https://jsa-rok.github.io/Information/
site_author: UrbanIndigo's Republic of Korea
site_description: Active Documentation Service for the Republic of Korea Roblox Group.
repo_name: JSA-ROK/Information
repo_url: https://github.com/JSA-ROK/Information

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.bottom
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate

plugins:
  - search:
      seperator: '[\s\-]+'
  - tags
  - awesome-pages
  - git-authors
  - git-revision-date-localized:
      type: date
  - section-index

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences